/**
 * Generate a TESTNET-ONLY wallet for the test agent.
 *
 * Run with:  npm run wallet:new
 *
 * SAFETY:
 *   - The key is written to .wallet-testnet.json, which is gitignored.
 *   - Testnet USDC has no monetary value. Losing this key costs nothing.
 *   - NEVER use this key, or this script, for mainnet. Production keys must
 *     never be generated by, stored on, or read by the server. See docs/SECURITY.md.
 */
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { writeFileSync, existsSync, chmodSync } from "node:fs";

const FILE = ".wallet-testnet.json";

if (existsSync(FILE)) {
  console.error(`${FILE} already exists. Delete it first if you want a fresh wallet.`);
  process.exit(1);
}

const privateKey = generatePrivateKey();
const account = privateKeyToAccount(privateKey);

writeFileSync(
  FILE,
  JSON.stringify(
    {
      WARNING: "TESTNET ONLY. Never fund this address with real money.",
      network: "base-sepolia",
      address: account.address,
      privateKey,
      createdAt: new Date().toISOString(),
    },
    null,
    2,
  ),
);
chmodSync(FILE, 0o600);

console.log(`
Testnet wallet created -> ${FILE}  (gitignored, mode 0600)

  Address: ${account.address}

This wallet is EMPTY. To run the paid test, fund it with free testnet USDC:

  1. Get Base Sepolia ETH for gas:
     https://www.alchemy.com/faucets/base-sepolia

  2. Get Base Sepolia USDC:
     https://faucet.circle.com   (choose "Base Sepolia")

  3. Add this line to your .env:
     TESTNET_PRIVATE_KEY=${privateKey}

Testnet funds are play money and cannot be converted to anything real.
`);
